# Generated by Django 2.2.28 on 2022-11-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatedModel',
        ),
    ]
